### PR TITLE
Plugin project name

### PR DESCRIPTION
**Pull request by adamf321**
- **What kind of change does this PR introduce?** (Bug fix, feature,
  docs update, ...)
  Bug fix
- **What is the current behavior?** (You can also link to an open issue
  here)
  You can enter different project and plugin names when running new-wp. This doesn't work correctly.
- **What is the new behavior (if this is a feature change)?**
  Enter a single project/plugin name when running new-wp
- **Does this PR introduce a breaking change?** (What changes might
  users need to make in their application due to this PR?)
  No
- **Other information**:

### CODE REVIEW

**Comment by adamf321** [comment]
@mitogh @Rulox I have a solution for the different name issue, #19 . However, it hangs at the end after completing, even though it all seems to run fine. Any ideas what might be going on?

**Comment by mitogh** [comment]
Is working fine on my end.
- What issues are you facing?
- Would you mind sharing a screenshot or output information?

**Comment by Rulox** [comment]
I've tested this, and I think the problem is that, at the end, you need to hit `enter` key ? To me, it seems that the process is finished, but some `input prompt` is still active.

**Comment by mitogh** [comment]
By running what command?

Thanks

**Comment by adamf321** [comment]
The command is `yo moxie-lean:new-wp`

**Comment by Rulox** [comment]
@mitogh yeah sorry with the `new-wp` It seems you have to hit enter at the end. 

http://snaps.getmoxied.net/0u0s220t3A3r

**Comment by mitogh** [comment]
I see thank you @Rulox @adamf321.

Will take a look ASAP. 👍

**Comment by mitogh** [comment]
Please take a look once you have a chance and let me know, if there is anything else to be done here.

Thanks.

**Comment by mitogh** [comment]
I'm going to fix other issues on this branch and merge with the other in order to have a single PR.

**Comment by adamf321** [comment]
@mitogh I don't think there's anything else to add...

**Comment by mitogh** [comment]
Updated!

**Pull request merged**
